require: rubocop-rails
AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - script/**/*
    - tmp/**/*
    - vendor/**/*
    - lib/**/*
    - Gemfile
    - features/**/*
    - spec/**/*
    - app/controllers/admins/passwords_controller.rb
    - app/controllers/admins/registrations_controller.rb
    - app/controllers/admins/sessions_controller.rb
    - app/controllers/users/passwords_controller.rb
    - app/controllers/users/registrations_controller.rb
    - app/controllers/users/sessions_controller.rb

# Rails用rubocop
Rails:
  Enabled: true

# １クラスの行数を200行以下に制限する
Metrics/ClassLength:
  Max: 200

# １行の文字数を制限しない
Metrics/LineLength:
  Enabled: false

# １メソッドの行数を制限しない
Metrics/MethodLength:
  Enabled: false

# 日本語コメントを許す
Style/AsciiComments:
  Enabled: false

# ファイル冒頭にコメントを書かなくてもよい
Style/Documentation:
  Enabled: false

# class Hoge::Fooのような記述を許す
Style/ClassAndModuleChildren:
  Enabled: false

# FrozenStringLiteralCommentを無視
Style/FrozenStringLiteralComment:
  Enabled: false

# ABC sizeの設定
Metrics/AbcSize:
  Enabled: true
  Max: 20

# html_safeを許可
Rails/OutputSafety:
  Enabled: false
