default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: popaisekine_development
  username: root

test:
  <<: *default
  database: popaisekine_test
  username: root

production:
  <<: *default
  database: popaisekine_production
